server:
  port: 8090

# Database connectivity
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_LOCAL_HOST:localhost}:${POSTGRES_LOCAL_PORT:5432}/${POSTGRES_DB:white_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

# Swagger
springdoc:
  swagger-ui:
    path: /api-ui
  api-docs:
    path: /api-docs